//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcademicCircleManagerApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AcademicCircleManagerApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.Koła naukowe.
        /// </summary>
        public static string AcademicCircle1 {
            get {
                return ResourceManager.GetString("AcademicCircle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koła Naukowe.
        /// </summary>
        public static string AcademicCircleCathegoryName {
            get {
                return ResourceManager.GetString("AcademicCircleCathegoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager kół naukowych.
        /// </summary>
        public static string AcademicCircleManager {
            get {
                return ResourceManager.GetString("AcademicCircleManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Członkowie kół.
        /// </summary>
        public static string AddEditMembers {
            get {
                return ResourceManager.GetString("AddEditMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj wydział.
        /// </summary>
        public static string AddFaculty {
            get {
                return ResourceManager.GetString("AddFaculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Attributes {
            get {
                object obj = ResourceManager.GetObject("Attributes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Narodowość:.
        /// </summary>
        public static string Background {
            get {
                return ResourceManager.GetString("Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anuluj.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przydział.
        /// </summary>
        public static string CircleForm {
            get {
                return ResourceManager.GetString("CircleForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miasto:.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elektryczny.
        /// </summary>
        public static string ELName {
            get {
                return ResourceManager.GetString("ELName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wydział:.
        /// </summary>
        public static string Faculty {
            get {
                return ResourceManager.GetString("Faculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wydział.
        /// </summary>
        public static string Faculty1 {
            get {
                return ResourceManager.GetString("Faculty1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imię:.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imię.
        /// </summary>
        public static string FirstName1 {
            get {
                return ResourceManager.GetString("FirstName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inżynierii Materiałowej.
        /// </summary>
        public static string IMName {
            get {
                return ResourceManager.GetString("IMName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zainteresowania.
        /// </summary>
        public static string Interests {
            get {
                return ResourceManager.GetString("Interests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Język.
        /// </summary>
        public static string LanguageSubcathegoryName {
            get {
                return ResourceManager.GetString("LanguageSubcathegoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwisko:.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwisko.
        /// </summary>
        public static string LastName1 {
            get {
                return ResourceManager.GetString("LastName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strona Główna.
        /// </summary>
        public static string MainPage {
            get {
                return ResourceManager.GetString("MainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Średnia:.
        /// </summary>
        public static string Mean {
            get {
                return ResourceManager.GetString("Mean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Członek koła.
        /// </summary>
        public static string MemberData {
            get {
                return ResourceManager.GetString("MemberData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista członków.
        /// </summary>
        public static string MemberList {
            get {
                return ResourceManager.GetString("MemberList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powrót.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dalej.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] NotoSerif_Bold {
            get {
                object obj = ResourceManager.GetObject("NotoSerif_Bold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] NotoSerif_BoldItalic {
            get {
                object obj = ResourceManager.GetObject("NotoSerif_BoldItalic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] NotoSerif_Condensed {
            get {
                object obj = ResourceManager.GetObject("NotoSerif_Condensed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] NotoSerif_CondensedBold {
            get {
                object obj = ResourceManager.GetObject("NotoSerif_CondensedBold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] NotoSerif_CondensedBoldItalic {
            get {
                object obj = ResourceManager.GetObject("NotoSerif_CondensedBoldItalic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] NotoSerif_CondensedItalic {
            get {
                object obj = ResourceManager.GetObject("NotoSerif_CondensedItalic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] NotoSerif_Light {
            get {
                object obj = ResourceManager.GetObject("NotoSerif_Light", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] NotoSerif_LightItalic {
            get {
                object obj = ResourceManager.GetObject("NotoSerif_LightItalic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] NotoSerif_Regular {
            get {
                object obj = ResourceManager.GetObject("NotoSerif_Regular", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer budynku:.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inne.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wróć.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer lokalu:.
        /// </summary>
        public static string SecondNumber {
            get {
                return ResourceManager.GetString("SecondNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod wydziału:.
        /// </summary>
        public static string ShortNameOfFaculty {
            get {
                return ResourceManager.GetString("ShortNameOfFaculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.Umiejętności.
        /// </summary>
        public static string Skills2 {
            get {
                return ResourceManager.GetString("Skills2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umiejętności.
        /// </summary>
        public static string SkillsCathegoryName {
            get {
                return ResourceManager.GetString("SkillsCathegoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umiejętności.
        /// </summary>
        public static string SKName {
            get {
                return ResourceManager.GetString("SKName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ul..
        /// </summary>
        public static string St {
            get {
                return ResourceManager.GetString("St", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulica:.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kierunek:.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transportu i Inżynierii Lotniczej.
        /// </summary>
        public static string TiILName {
            get {
                return ResourceManager.GetString("TiILName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rok:.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rok.
        /// </summary>
        public static string Year1 {
            get {
                return ResourceManager.GetString("Year1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tak.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane menadżera.
        /// </summary>
        public static string YourData {
            get {
                return ResourceManager.GetString("YourData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod pocztowy:.
        /// </summary>
        public static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
    }
}
